### ISSUE TITLE
/usr/local/wamedia require privileges for kubernetes 

### ISSUE THREAD

**Issue by sneerin** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#16]
on GKE path for Kubernetes causing crash since GKE got security settings enabled for /usr/ path, replacing the path fix the issue

**Comment by mengyiyuan** [comment]
Hi,

Not 100% sure if I understand you. Are you saying that the user permission required for `/usr/local/wamedia` caused pods to crash on GKE because GKE has security limitations on /usr/ and all its subdirectories?

And you fixed it by changing the mountPath to another path?

**Comment by sneerin** [comment]
Both, on another bare metal k8s setup it was just failing to start without crashing probably also due to the same reason. Replacing to /var/wamedia did the trick.

**Comment by mengyiyuan** [comment]
Thanks for reporting this issue. Not quite sure what we should do in this case, please use the templates as a starting point/reference only, you may need to change things based on your system requirements, because it is difficult to cover all cases.

I'll close the issue for now, because I don't think any actions need to be taken here.

Thanks!
