### ISSUE TITLE
Issue connecting to the server

### ISSUE THREAD

**Issue by OLayemii** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#20]
I followed the installation instructions from https://developers.facebook.com/docs/whatsapp/installation/dev-single-instance for Developer Setup: Single Instance, and i have everything up and running but going to http:MY_URL:9090 from my browser, I get an "Unable to connect page"

Is there anything I am doing wrong?

**Comment by Rajamohanreddyai** [comment]
Hello,

I was created the whole setup at that time I got the same error, but at the next second I was fixed the same. Mainly because of 2 reasons you may get the URL not found errors.

Containers are not up (db, coreapp, webapp).
You might be calling the wrong URL.
Please check the below link if do you want any clarity. https://youtu.be/hYO32rQQ9Pc
