### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by techwitz** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#21]
Hi

I have downloaded/cloned to git repository and I am getting while executing command to pull docker images.

docker-compose up -d

> Pulling wacore (docker.whatsapp.biz/coreapp:vv2.27.8)...
> ERROR: manifest for docker.whatsapp.biz/coreapp:vv2.27.8 not found: manifest unknown: The named manifest is not known to the registry.

Please suggest.

Thanks

**Comment by techwitz** [comment]
Sorry, I configured wrong version i.e. prefixed 'v' with version

**Comment by Rajamohanreddyai** [comment]
Hello,

I was created the whole setup at that time I got the same error, but at the next second I was fixed the same. Mainly because of 2 reasons you may get the URL not found errors.

Containers are not up (db, coreapp, webapp).
You might be calling the wrong URL.
Please check the below link if do you want any clarity. https://youtu.be/hYO32rQQ9Pc
