### ISSUE TITLE
Postman socket hang up

### ISSUE THREAD

**Issue by Ref-Bit** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#39]
Hi, I have just installed Whatsapp Business API through [Developer Setup: Single Instance](https://developers.facebook.com/docs/whatsapp/installation/dev-single-instance), but when I reached the testing point with Postman, it throws an **"Error: socket hang up"**. 
I have followed both Initial Setup provided here in docs and [Postman first setup](https://developers.facebook.com/docs/whatsapp/guides/postman#first-time-setup) carefully.
Thank you.

**Comment by Ref-Bit** [comment]
I solved the problem by changing _localhost_ to _127.0.0.1_

**Comment by Rajamohanreddyai** [comment]
Hello ,

I was created the whole setup at that time I got the same error, but at the next second I was fixed the same. Mainly because of 2 reasons you may get the URL not found errors.

Containers are not up (db, coreapp, webapp).
You might be calling the wrong URL.
Please check the below link if do you want any clarity. https://youtu.be/hYO32rQQ9Pc
