### ISSUE TITLE
ERROR: error pulling image configuration: error parsing HTTP 403 response body:

### ISSUE THREAD

**Issue by harshrathod50** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#51]
I get this error that I don't understand:

```
[root@localhost mark42]# docker-compose up -d
Pulling wacore (docker.whatsapp.biz/coreapp:v2.31.4)...
v2.31.4: Pulling from coreapp
4f53fa4d2cf0: Pulling fs layer
6af7c939e38e: Pulling fs layer
903d0ffd64f6: Pulling fs layer
04feeed388b7: Waiting
5e8b3db3500c: Waiting
3753a44ac819: Waiting
18bf76221b51: Waiting
699200463962: Waiting
427d537c1a25: Waiting
6b9dde11b413: Waiting
6a72a02a430e: Waiting
b8e062498aae: Waiting
ebe407c760a1: Waiting
ERROR: error pulling image configuration: error parsing HTTP 403 response body:
invalid character 'F' looking for beginning of value: "Forbidden!"
```

I also have one question: how and where can I know the right value of WA_API_VERSION environment variable?

**Comment by Wouterrr** [comment]
Hey Harsh Rathod,

Please use the changelog to track the latest versions. 
https://developers.facebook.com/docs/whatsapp/changelog

I was unable to reproduce your issue. Please retry to confirm it's not a network issue.

If the issue persists, and if you are an official partner of the WhatsApp Business API, please use the support channel available to you there, which will have better coverage.

**Comment by Rajamohanreddyai** [comment]
Hello Harsh Rathod,

I was created the whole setup at that time I got the same error, but at the next second I was fixed the same. Mainly because of 2 reasons you may get the URL not found errors.

Containers are not up (db, coreapp, webapp).
You might be calling the wrong URL.
Please check the below link if do you want any clarity. https://youtu.be/hYO32rQQ9Pc
