### ISSUE TITLE
db.env config file 

### ISSUE THREAD

**Issue by massimiliano-derosa** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#9]
Hi, the file db.env have a wrong configuration.

-> WRONG WA_DB_PORT=3306
-> CORRECT WA_DB_PORT=33060

Regards
Massimiliano & Fausto

**Comment by mengyiyuan** [comment]
Hi Massimiliano & Fausto,

WA_DB_PORT=3306 is correct when you use docker-compose.yml file.

Using docker-compose, you can refer to another service using the name of the service. As WA_DB_HOSTNAME in db.env is `db`,  which is the name of the service, the port is the container port respectively.

Did you have issues installing using WA_DB_PORT=3306?

**Comment by mengyiyuan** [comment]
For k8s setup, please use scripts from https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/tree/master/installation/kubernetes, instead of the docker-compose files. The docs are here: https://developers.facebook.com/docs/whatsapp/installation/dev-multiconnect-minikube

To provide a documentation for production environment, we are also trying to get feedback about what k8s environment you use for your production system, are you using OpenShift? In what format, will you like the scripts to be presented?

**Comment by jeet-from-win** [comment]
My firm wanted to be a solution provider for Whatsapp Business API. I haven't found any documentation for above. I just found the registration form. How would I able to know, What are the requirements of Whatsapp and Facebook for allowing a firm to be a solution provider for their services?

**Comment by thiagocmoraes** [comment]
> My firm wanted to be a solution provider for Whatsapp Business API. I haven't found any documentation for above. I just found the registration form. How would I able to know, What are the requirements of Whatsapp and Facebook for allowing a firm to be a solution provider for their services?

The product is still in closed beta and the registration form is the best way to keep up with our future releases. Thanks for the interest and hopefully we can expand access soon.
